In [ ]:
  import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/indian_student_dirty_dataset_realistic (3).csv')
df.head()

,Student_ID,Name,Age,Gender,Caste_Category,City,State,College_Name,Course,Department,Admission_Year,Year_of_Study,CGPA,Attendance_Percentage,Annual_Fees,Scholarship_Status,Hostel_Resident
0,1,Student_1,21.0,NaN,ST,Solapur,NaN,Savitribai Phule Pune University,BSc,AIDS,NaN,5.0,8.5,95.0,0.0,NaN,Y
1,2,Student_2,NaN,NaN,SC,Nashik,maharashtra,Savitribai Phule Pune University,BSc,Computer,2023.0,5.0,7.9,55.0,90000.0,yes,NaN
2,3,Student_3,20.0,Male,SC,mumbai,Kerala,IIT Bombay,B.Tech,AIDS,2019.0,4.0,-1.0,95.0,120000.0,No,No
3,4,Student_4,20.0,Female,NaN,Nashik,Uttar Pradesh,Savitribai Phule Pune University,BSc,Civil,2023.0,4.0,6.8,55.0,45000.0,yes,Yes
4,5,Student_5,200.0,NaN,SC,Mumbai,Gujarat,Government Polytechnic Pune,MBA,AI&DS,2021.0,2.0,-1.0,65.0,35000.0,NaN,N

##1) Replacing Blanks with Nan

In [ ]:
print("Initial Dataset Preview")
df.info()

print("\n Dataset Info")
df.info()

print("\n Missing Values (Before Cleaning)")
display(df.isnull().sum())

df.head

Initial Dataset Preview
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             1000 non-null   int64
 1   Name                   1000 non-null   object
 2   Age                    883 non-null    float64
 3   Gender                 711 non-null    object
 4   Caste_Category         773 non-null    object
 5   City                   897 non-null    object
 6   State                  875 non-null    object
 7   College_Name           856 non-null    object
 8   Course                 870 non-null    object
 9   Department             882 non-null    object
 10  Admission_Year         887 non-null    float64
 11  Year_of_Study          834 non-null    float64
 12  CGPA                   889 non-null    float64
 13  Attendance_Percentage  882 non-null    float64
 14  Annual_Fees            873 non-null    float64
 15  Scholarship_Status     666 non-null    object
 16  Hostel_Resident        662 non-null    object
dtypes: float64(6), int64(1), object(10)
memory usage: 132.9+ KB

 Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             1000 non-null   int64
 1   Name                   1000 non-null   object
 2   Age                    883 non-null    float64
 3   Gender                 711 non-null    object
 4   Caste_Category         773 non-null    object
 5   City                   897 non-null    object
 6   State                  875 non-null    object
 7   College_Name           856 non-null    object
 8   Course                 870 non-null    object
 9   Department             882 non-null    object
 10  Admission_Year         887 non-null    float64
 11  Year_of_Study          834 non-null    float64
 12  CGPA                   889 non-null    float64
 13  Attendance_Percentage  882 non-null    float64
 14  Annual_Fees            873 non-null    float64
 15  Scholarship_Status     666 non-null    object
 16  Hostel_Resident        662 non-null    object
dtypes: float64(6), int64(1), object(10)
memory usage: 132.9+ KB

 Missing Values (Before Cleaning)

Student_ID                 0
Name                       0
Age                      117
Gender                   289
Caste_Category           227
City                     103
State                    125
College_Name             144
Course                   130
Department               118
Admission_Year           113
Year_of_Study            166
CGPA                     111
Attendance_Percentage    118
Annual_Fees              127
Scholarship_Status       334
Hostel_Resident          338
dtype: int64

<bound method NDFrame.head of      Student_ID          Name    Age  Gender Caste_Category     City  \
0             1     Student_1   21.0     NaN             ST  Solapur
1             2     Student_2    NaN     NaN             SC   Nashik
2             3     Student_3   20.0    Male             SC   mumbai
3             4     Student_4   20.0  Female            NaN   Nashik
4             5     Student_5  200.0     NaN             SC   Mumbai
..          ...           ...    ...     ...            ...      ...
995         996   Student_996   19.0     NaN            OBC   mumbai
996         997   Student_997   18.0     NaN            obc   Mumbai
997         998   Student_998   -3.0       F            NaN   mumbai
998         999   Student_999   19.0    Male            OBC     Pune
999        1000  Student_1000   -3.0       M            NaN   Nashik

             State                      College_Name   Course Department  \
0              NaN  Savitribai Phule Pune University      BSc       AIDS
1      maharashtra  Savitribai Phule Pune University      BSc   Computer
2           Kerala                        IIT Bombay   B.Tech       AIDS
3    Uttar Pradesh  Savitribai Phule Pune University      BSc      Civil
4          Gujarat       Government Polytechnic Pune      MBA      AI&DS
..             ...                               ...      ...        ...
995        Gujarat                              SPPU      NaN      AI&DS
996  Uttar Pradesh       Government Polytechnic Pune      mba       AIDS
997    maharashtra                 Mumbai University  B.Tech    Computer
998         Kerala                 Mumbai University   B.Tech   Computer
999            NaN                 Mumbai University      NaN      AI&DS

     Admission_Year  Year_of_Study  CGPA  Attendance_Percentage  Annual_Fees  \
0               NaN            5.0   8.5                   95.0          0.0
1            2023.0            5.0   7.9                   55.0      90000.0
2            2019.0            4.0  -1.0                   95.0     120000.0
3            2023.0            4.0   6.8                   55.0      45000.0
4            2021.0            2.0  -1.0                   65.0      35000.0
..              ...            ...   ...                    ...          ...
995          2020.0            5.0   NaN                   45.0          NaN
996          1890.0            3.0   6.8                    NaN      65000.0
997          2023.0            3.0  -1.0                   45.0     120000.0
998          2023.0            NaN   5.6                   75.0      45000.0
999          2020.0            NaN   5.6                   45.0          NaN

    Scholarship_Status Hostel_Resident
0                  NaN               Y
1                  yes             NaN
2                   No              No
3                  yes             Yes
4                  NaN               N
..                 ...             ...
995                NaN               Y
996                 No             Yes
997                yes               N
998                yes             Yes
999                NaN             NaN

[1000 rows x 17 columns]>

##2) Handle Missing Values

In [ ]:
# Numerical columns
num_cols = ["Age", "CGPA", "Attendance_Percentage",
            "Annual_Fees", "Year_of_Study", "Admission_Year"]

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

# Categorical columns
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipython-input-1497824200.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipython-input-1497824200.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

##3) Remove Noicy / Invalid Data

In [ ]:
# Age should be between 17 and 25
df.loc[(df["Age"] < 17) | (df["Age"] > 25), "Age"] = df["Age"].median()

# CGPA should be between 0 and 10
df.loc[(df["CGPA"] < 0) | (df["CGPA"] > 10), "CGPA"] = df["CGPA"].median()

# Attendance should be between 0 and 100
df.loc[(df["Attendance_Percentage"] < 0) |
       (df["Attendance_Percentage"] > 100),
       "Attendance_Percentage"] = df["Attendance_Percentage"].median()

# Admission Year should be between 2015 and 2025
df.loc[(df["Admission_Year"] < 2015) |
       (df["Admission_Year"] > 2025),
       "Admission_Year"] = df["Admission_Year"].median()

# Annual Fees should not be negative
df.loc[df["Annual_Fees"] < 0, "Annual_Fees"] = df["Annual_Fees"].median()

##4) Fix Inconsistent Data

In [ ]:
# Gender standardization
df["Gender"] = df["Gender"].str.lower().replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
})

# City and State formatting
df["City"] = df["City"].str.title()
df["State"] = df["State"].str.title()

# Fix state short form
df["State"] = df["State"].replace({"Up": "Uttar Pradesh"})

##5) Clean Course Column

In [ ]:
df["Course"] = df["Course"].str.strip().replace({
    "Btech": "B.Tech",
    "BSc": "B.Sc",
    "mba": "MBA"
})

##6️) Fix Department Column

In [ ]:
df["Department"] = df["Department"].replace({
    "AIDS": "AI&DS"
})

##7️) Caste Category Formatting

In [ ]:
df["Caste_Category"] = df["Caste_Category"].str.upper()

##8️) Standardize Binary Columns

In [ ]:
binary_map = {
    "Y": "Yes", "y": "Yes", "yes": "Yes",
    "N": "No",  "n": "No",  "no": "No"
}

df["Scholarship_Status"] = df["Scholarship_Status"].replace(binary_map)
df["Hostel_Resident"] = df["Hostel_Resident"].replace(binary_map)

In [ ]:
print("Data Cleaning Completed Successfully ✅")

Data Cleaning Completed Successfully ✅

In [ ]:
df

,Student_ID,Name,Age,Gender,Caste_Category,City,State,College_Name,Course,Department,Admission_Year,Year_of_Study,CGPA,Attendance_Percentage,Annual_Fees,Scholarship_Status,Hostel_Resident
0,1,Student_1,21.0,Male,ST,Solapur,Uttar Pradesh,Savitribai Phule Pune University,B.Sc,AI&DS,2020.0,5.0,8.5,95.0,0.0,No,Yes
1,2,Student_2,19.0,Male,SC,Nashik,Maharashtra,Savitribai Phule Pune University,B.Sc,Computer,2023.0,5.0,7.9,55.0,90000.0,Yes,Yes
2,3,Student_3,20.0,Male,SC,Mumbai,Kerala,IIT Bombay,B.Tech,AI&DS,2019.0,4.0,6.8,95.0,120000.0,No,No
3,4,Student_4,20.0,Female,OPEN,Nashik,Uttar Pradesh,Savitribai Phule Pune University,B.Sc,Civil,2023.0,4.0,6.8,55.0,45000.0,Yes,Yes
4,5,Student_5,19.0,Male,SC,Mumbai,Gujarat,Government Polytechnic Pune,MBA,AI&DS,2021.0,2.0,6.8,65.0,35000.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,19.0,Male,OBC,Mumbai,Gujarat,SPPU,B.Sc,AI&DS,2020.0,5.0,6.8,45.0,45000.0,No,Yes
996,997,Student_997,18.0,Male,OBC,Mumbai,Uttar Pradesh,Government Polytechnic Pune,MBA,AI&DS,2020.0,3.0,6.8,75.0,65000.0,No,Yes
997,998,Student_998,19.0,Female,OPEN,Mumbai,Maharashtra,Mumbai University,B.Tech,Computer,2023.0,3.0,6.8,45.0,120000.0,Yes,No
998,999,Student_999,19.0,Male,OBC,Pune,Kerala,Mumbai University,B.Tech,Computer,2023.0,3.0,5.6,75.0,45000.0,Yes,Yes
999,1000,Student_1000,19.0,Male,OPEN,Nashik,Uttar Pradesh,Mumbai University,B.Sc,AI&DS,2020.0,3.0,5.6,45.0,45000.0,No,Yes

In [ ]:
print("Initial Dataset Preview")
df.info()

print("\n Dataset Info")
df.info()

print("\n Missing Values (Before Cleaning)")
display(df.isnull().sum())

df.head

Initial Dataset Preview
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             1000 non-null   int64
 1   Name                   1000 non-null   object
 2   Age                    1000 non-null   float64
 3   Gender                 1000 non-null   object
 4   Caste_Category         1000 non-null   object
 5   City                   1000 non-null   object
 6   State                  1000 non-null   object
 7   College_Name           1000 non-null   object
 8   Course                 1000 non-null   object
 9   Department             1000 non-null   object
 10  Admission_Year         1000 non-null   float64
 11  Year_of_Study          1000 non-null   float64
 12  CGPA                   1000 non-null   float64
 13  Attendance_Percentage  1000 non-null   float64
 14  Annual_Fees            1000 non-null   float64
 15  Scholarship_Status     1000 non-null   object
 16  Hostel_Resident        1000 non-null   object
dtypes: float64(6), int64(1), object(10)
memory usage: 132.9+ KB

 Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             1000 non-null   int64
 1   Name                   1000 non-null   object
 2   Age                    1000 non-null   float64
 3   Gender                 1000 non-null   object
 4   Caste_Category         1000 non-null   object
 5   City                   1000 non-null   object
 6   State                  1000 non-null   object
 7   College_Name           1000 non-null   object
 8   Course                 1000 non-null   object
 9   Department             1000 non-null   object
 10  Admission_Year         1000 non-null   float64
 11  Year_of_Study          1000 non-null   float64
 12  CGPA                   1000 non-null   float64
 13  Attendance_Percentage  1000 non-null   float64
 14  Annual_Fees            1000 non-null   float64
 15  Scholarship_Status     1000 non-null   object
 16  Hostel_Resident        1000 non-null   object
dtypes: float64(6), int64(1), object(10)
memory usage: 132.9+ KB

 Missing Values (Before Cleaning)

Student_ID               0
Name                     0
Age                      0
Gender                   0
Caste_Category           0
City                     0
State                    0
College_Name             0
Course                   0
Department               0
Admission_Year           0
Year_of_Study            0
CGPA                     0
Attendance_Percentage    0
Annual_Fees              0
Scholarship_Status       0
Hostel_Resident          0
dtype: int64

<bound method NDFrame.head of      Student_ID          Name   Age  Gender Caste_Category     City  \
0             1     Student_1  21.0    Male             ST  Solapur
1             2     Student_2  19.0    Male             SC   Nashik
2             3     Student_3  20.0    Male             SC   Mumbai
3             4     Student_4  20.0  Female           OPEN   Nashik
4             5     Student_5  19.0    Male             SC   Mumbai
..          ...           ...   ...     ...            ...      ...
995         996   Student_996  19.0    Male            OBC   Mumbai
996         997   Student_997  18.0    Male            OBC   Mumbai
997         998   Student_998  19.0  Female           OPEN   Mumbai
998         999   Student_999  19.0    Male            OBC     Pune
999        1000  Student_1000  19.0    Male           OPEN   Nashik

             State                      College_Name  Course Department  \
0    Uttar Pradesh  Savitribai Phule Pune University    B.Sc      AI&DS
1      Maharashtra  Savitribai Phule Pune University    B.Sc   Computer
2           Kerala                        IIT Bombay  B.Tech      AI&DS
3    Uttar Pradesh  Savitribai Phule Pune University    B.Sc      Civil
4          Gujarat       Government Polytechnic Pune     MBA      AI&DS
..             ...                               ...     ...        ...
995        Gujarat                              SPPU    B.Sc      AI&DS
996  Uttar Pradesh       Government Polytechnic Pune     MBA      AI&DS
997    Maharashtra                 Mumbai University  B.Tech   Computer
998         Kerala                 Mumbai University  B.Tech   Computer
999  Uttar Pradesh                 Mumbai University    B.Sc      AI&DS

     Admission_Year  Year_of_Study  CGPA  Attendance_Percentage  Annual_Fees  \
0            2020.0            5.0   8.5                   95.0          0.0
1            2023.0            5.0   7.9                   55.0      90000.0
2            2019.0            4.0   6.8                   95.0     120000.0
3            2023.0            4.0   6.8                   55.0      45000.0
4            2021.0            2.0   6.8                   65.0      35000.0
..              ...            ...   ...                    ...          ...
995          2020.0            5.0   6.8                   45.0      45000.0
996          2020.0            3.0   6.8                   75.0      65000.0
997          2023.0            3.0   6.8                   45.0     120000.0
998          2023.0            3.0   5.6                   75.0      45000.0
999          2020.0            3.0   5.6                   45.0      45000.0

    Scholarship_Status Hostel_Resident
0                   No             Yes
1                  Yes             Yes
2                   No              No
3                  Yes             Yes
4                   No              No
..                 ...             ...
995                 No             Yes
996                 No             Yes
997                Yes              No
998                Yes             Yes
999                 No             Yes

[1000 rows x 17 columns]>